spring:
  profiles:
    active: local
server:
  baseUrl: http://localhost:3000/
  imageUrl: images/

---
spring:
  profiles: local
server:
  baseUrl: http://s3-ap-southeast-1.amazonaws.com/se331/
  imageUrl: pics/
